SHELL := /bin/bash
NAME := REPLACE_ME_APP_NAME
OS := $(shell uname)

all: build

check: build test

build:
	echo "do nothing"

test: 
	echo "do nothing"

install:
	echo "do nothing"

clean:
	rm -rf build release

linux:
	echo "do nothing"

.PHONY: release clean
