pipeline {
  agent {
    label "jenkins-maven"
  }
  environment {
    ORG               = 'REPLACE_ME_ORG'
    APP_NAME          = 'REPLACE_ME_APP_NAME'
    CHARTMUSEUM_CREDS = credentials('jenkins-x-chartmuseum')
    MAVEN_HOME        = '$M2_HOME'
    JAVA_HOME         = "/usr/lib/jvm/java"
  }
  stages {
    stage('CI Build and push snapshot') {
      when {
        branch 'PR-*'
      }
      environment {
        PREVIEW_VERSION = "0.0.0-SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER"
        PREVIEW_NAMESPACE = "$APP_NAME-$BRANCH_NAME".toLowerCase()
        HELM_RELEASE = "$PREVIEW_NAMESPACE".toLowerCase()
      }
      steps {
        configArtifactoryStage()
        container('maven') {
          runMaven("versions:set -DnewVersion=" + "$PREVIEW_VERSION", null)
          runMaven("install", null)
          sh 'export VERSION=$PREVIEW_VERSION && skaffold run -f skaffold.yaml'

          sh "jx step validate --min-jx-version 1.2.36"
          sh "jx step post build --image \$JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST:\$JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT/$ORG/$APP_NAME:$PREVIEW_VERSION"
        }

        dir ('./charts/preview') {
          container('maven') {
            sh "make preview"
            sh "jx preview --app $APP_NAME --dir ../.."
          }
        }
      }
    }
    stage('Build Release') {
      when {
        branch 'master'
      }
      steps {
        configArtifactoryStage()
        container('maven') {
          // ensure we're not on a detached head
          sh "git checkout master"
          sh "git config --global credential.helper store"
          sh "jx step validate --min-jx-version 1.1.73"
          sh "jx step git credentials"
          // so we can retrieve the version in later steps
          sh "echo \$(jx-release-version) > VERSION"
          runMaven("versions:set -DnewVersion=\$(jx-release-version)", null)
        }
        dir ('./charts/REPLACE_ME_APP_NAME') {
          container('maven') {
            sh "make tag"
          }
        }
        container('maven') {
          deploy()

          sh 'export VERSION=`cat VERSION` && skaffold run -f skaffold.yaml'

          sh "jx step validate --min-jx-version 1.2.36"
          sh "jx step post build --image \$JENKINS_X_DOCKER_REGISTRY_SERVICE_HOST:\$JENKINS_X_DOCKER_REGISTRY_SERVICE_PORT/$ORG/$APP_NAME:\$(cat VERSION)"
        }
      }
    }
    stage('Promote to Environments') {
      when {
        branch 'master'
      }
      steps {
        dir ('./charts/REPLACE_ME_APP_NAME') {
          container('maven') {
            sh 'jx step changelog --version v\$(cat ../../VERSION)'

            // release the helm chart
            sh 'make release'

            // promote through all 'Auto' promotion Environments
            sh 'jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)'
          }
        }
      }
    }
  }
  post {
    always {
      cleanWs()
    }
    failure {
      input """Pipeline failed. 
We will keep the build pod around to help you diagnose any failures. 

Select Proceed or Abort to terminate the build pod"""
    }
  }
}

def rtServer, buildInfo, rtMaven
void configArtifactoryStage() {
  script {
    if (useArtifactory()) {
      rtServer = Artifactory.server "JX_ARTIFACTORY_SERVER"
      buildInfo = Artifactory.newBuildInfo()
      rtMaven = Artifactory.newMavenBuild()
      rtMaven.deployer releaseRepo: 'libs-release-local', snapshotRepo: 'libs-snapshot-local', server: rtServer
      rtMaven.resolver releaseRepo: 'libs-release', snapshotRepo: 'libs-snapshot', server: rtServer
      rtMaven.deployer.deployArtifacts = false
    }
  }
}

void runMaven(goals, buildInfo) {
  script {
    if (useArtifactory()) {
      rtMaven.run pom: 'pom.xml', goals: goals, buildInfo: buildInfo
    } else {
      sh "mvn " + goals
    }
  }
}

void deploy() {
  script {
    if (useArtifactory()) {
      runMaven("install", buildInfo)
      rtMaven.deployer.deployArtifacts buildInfo
      rtServer.publishBuildInfo buildInfo
    } else {
      runMaven("clean deploy", null)
    }
  }
}

boolean useArtifactory() {
  script {
    try {
      return Artifactory != null && Artifactory.server("JX_ARTIFACTORY_SERVER") != null
    } catch (ignored) {
      return false
    }
  }
}